# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*
- release/3.0.0

pool:
  vmImage: 'macos-latest'

variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_0_0_FULL.zip?_ga=2.79185814.368877217.1583320605-5559409.1503304822'
  MacRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_0_0_FULL.zip?_ga=2.78400662.368877217.1583320605-5559409.1503304822'
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v3_0_0_FULL.zip'
  ConnectionName: sbd021
  RepoName: AgoraIO

jobs:

- template: Android/azure-templates/build-android.yml
  parameters:
    project: 'Android'
    module: 'sample-switch-external-video'
    name: 'SwitchVideoInputAndroid'

- template: Android/azure-templates/build-android.yml
  parameters:
    project: 'Android'
    module: 'sample-video-encrypt'
    name: 'VideoEncryptionAndroid'

- template: Android/azure-templates/build-android.yml
  parameters:
    project: 'Android'
    module: 'sample-custom-render'
    name: 'CustomRendererAndroid'

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraCustomMediaDevice'
    workingDirectory: 'iOS&macOS/Agora-Custom-Media-Device'
    scheme: 'Agora-Custom-Media-Device'
    sdkurl: $(iOSRTCSDK)

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraPluginRawDataAPIiOSObjectiveC'
    workingDirectory: 'iOS&macOS/Agora-Plugin-Raw-Data-API-Objective-C'
    scheme: 'Agora-Plugin-Raw-Data-API-iOS-Objective-C'
    sdkurl: $(iOSRTCSDK)
    
- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraScreenSharing'
    workingDirectory: 'iOS&macOS/Agora-Screen-Sharing'
    scheme: 'Agora-Plugin-Raw-Data-API-iOS-Objective-C'
    sdkurl: $(iOSRTCSDK)

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraVideoSource'
    workingDirectory: 'iOS&macOS/Agora-Video-Source'
    scheme: 'Agora-Screen-Sharing'
    sdkurl: $(iOSRTCSDK)

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraVideoWithARKit'
    workingDirectory: 'iOS&macOS/Agora-Video-With-ARKit'
    scheme: 'Agora-Video-With-ARKit'
    sdkurl: $(iOSRTCSDK)

#Windows Demo
- template: Windows/cicd/templates/build-Windows.yml
  parameters:
    displayName: 'AgoraStringAccountWindows'
    workingDirectory: 'Windows/Agora-String-Account-Windows'
    scheme: 'Agora-String-Account-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'OpenLive.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'

- template: Windows/cicd/templates/build-Windows.yml
  parameters:
    displayName: 'LargeGroupVideoChatWindows'
    workingDirectory: 'Windows/LargeGroupVideoChat-Windows'
    scheme: 'LargeGroupVideoChat-Windowss'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraOpenLive.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'

- template: Windows/cicd/templates/build-Windows.yml
  parameters:
    displayName: 'AgoraScreenSharingWindows'
    workingDirectory: 'Windows/Agora-Screen-Sharing-Windows'
    scheme: 'Agora-Screen-Sharing-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'OpenLive.sln'
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'

#hook demo
- template: Windows/cicd/templates/build-Windows-Extend.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindows'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows'
    scheme: 'Agora-RTC-Hooking-API-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraHooking.sln'
    downloadGithubSDK: HookSDK.zip
    connectionName: $(ConnectionName)
    userRepository: $(RepoName)/Advanced-Video
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'

- template: Windows/cicd/templates/build-Windows-Extend.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindowskuwo'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows-kuwo'
    scheme: 'Agora-RTC-Hooking-API-Windows-kuwo'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraHooking.sln'
    downloadGithubSDK: HookSDK.zip
    connectionName: $(ConnectionName)
    userRepository: $(RepoName)/Advanced-Video
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'

- template: Windows/cicd/templates/build-Windows-Extend.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindowsyingyonghuyu'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows-yingyonghuyu'
    scheme: 'Agora-RTC-Hooking-API-Windows-yingyonghuyu'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraHooking.sln'
    downloadGithubSDK: HookSDK.zip
    connectionName: $(ConnectionName)
    userRepository: $(RepoName)/Advanced-Video
    sdkunzipPath: 'AgoraSDK/Agora_Native_SDK_for_Windows_v3.0.0_FULL'