# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*
- release/3.0.0

pool:
  vmImage: 'macos-latest'

variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_0_0_FULL.zip?_ga=2.79185814.368877217.1583320605-5559409.1503304822'
  MacRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_0_0_FULL.zip?_ga=2.78400662.368877217.1583320605-5559409.1503304822'
jobs:
#Windows Demo
#hook demo
- template: Windows/cicd/templates/build-Windows-Hook.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindows'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows'
    scheme: 'Agora-RTC-Hooking-API-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraHooking.sln'
    downloadGithubSDK: HookSDK.zip
    sdkVersion: '3_0_0'
    sdkFolderVersion: '3.0.0'
    Machine: x86 

- template: Windows/cicd/templates/build-Windows-Hook.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindowskuwo'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows-kuwo'
    scheme: 'Agora-RTC-Hooking-API-Windows-kuwo'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraHooking.sln'
    downloadGithubSDK: HookSDK.zip
    sdkVersion: '3_0_0'
    sdkFolderVersion: '3.0.0'
    Machine: x86 

- template: Windows/cicd/templates/build-Windows-Hook.yml
  parameters:
    displayName: 'AgoraRTCHookingAPIWindowsyingyonghuyu'
    workingDirectory: 'Windows/Agora-RTC-Hooking-API-Windows-yingyonghuyu'
    scheme: 'Agora-RTC-Hooking-API-Windows-yingyonghuyu'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraHooking.sln'
    sdkVersion: '3_0_0'
    sdkFolderVersion: '3.0.0'
    Machine: x86 

- template: Windows/cicd/templates/build-Windows-dshow.yml
  parameters:
    displayName: 'AgoraMediaSourceWindows'
    workingDirectory: 'Windows/Agora-Media-Source-Windows'
    scheme: 'Agora-Media-Source-Windows'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'AgoraMediaSource.sln'
    sdkVersion: '3_0_0'
    sdkFolderVersion: '3.0.0'
    Machine: x86
